import { ClerkProvider } from "@clerk/nextjs";
import { cn } from "lib";
import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";
import "./globals.css";
import { CountriesProvider } from "contexts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fonts = JetBrains_Mono({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <NuqsAdapter>
        <CountriesProvider>
          <html lang="en" className={cn("", fonts.className)}>
            <body>{children}</body>
          </html>
        </CountriesProvider>
      </NuqsAdapter>
    </ClerkProvider>
  );
}
